"""make refresh_token nullable on connections

Revision ID: 253a989eeb1c
Revises: fa3edbf3d2d8
Create Date: 2026-08-09 13:12:04.108984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253a989eeb1c'
down_revision: Union[str, Sequence[str], None] = 'fa3edbf3d2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
