"""add unique constraint on connections org and provider

Revision ID: 3f71f604a355
Revises: 253a989eeb1c
Create Date: 2026-08-11 11:21:03.330473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f71f604a355'
down_revision: Union[str, Sequence[str], None] = '253a989eeb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_connection_org_provider', 'connections', ['organization_id', 'provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_connection_org_provider', 'connections', type_='unique')
    # ### end Alembic commands ###
