"""cascade delete on connections and endpoints

Revision ID: 885230519740
Revises: 3f71f604a355
Create Date: 2026-08-11 11:52:18.041114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885230519740'
down_revision: Union[str, Sequence[str], None] = '3f71f604a355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('connections_organization_id_fkey'), 'connections', type_='foreignkey')
    op.drop_constraint(op.f('connections_provider_id_fkey'), 'connections', type_='foreignkey')
    op.create_foreign_key('fk_connections_provider_id', 'connections', 'providers', ['provider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_connections_organization_id', 'connections', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('endpoints_provider_id_fkey'), 'endpoints', type_='foreignkey')
    op.create_foreign_key('fk_endpoints_provider_id', 'endpoints', 'providers', ['provider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_endpoints_provider_id', 'endpoints', type_='foreignkey')
    op.create_foreign_key(op.f('endpoints_provider_id_fkey'), 'endpoints', 'providers', ['provider_id'], ['id'])
    op.drop_constraint('fk_connections_organization_id', 'connections', type_='foreignkey')
    op.drop_constraint('fk_connections_provider_id', 'connections', type_='foreignkey')
    op.create_foreign_key(op.f('connections_provider_id_fkey'), 'connections', 'providers', ['provider_id'], ['id'])
    op.create_foreign_key(op.f('connections_organization_id_fkey'), 'connections', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
