"""add token_url to providers

Revision ID: a6ad1484eb49
Revises: 75ab2b4ef50e
Create Date: 2026-08-17 19:21:55.408614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ad1484eb49'
down_revision: Union[str, Sequence[str], None] = '75ab2b4ef50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('token_url', sa.String(length=255), nullable=False,server_default='https://example.com/oauth/token'))
    op.alter_column('providers','token_url',server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'token_url')
    # ### end Alembic commands ###

